### ISSUE TITLE
電源を切ってもスタックがクリアされない ようにできないでしょうか。

### ISSUE THREAD

**Issue by ypsilon-takai** [ypsilon-takai/hobby-rpn#11]
@WarabiMkV さんからの要望です。

**Comment by ypsilon-takai** [comment]
修正用ブランチpreserve_stacに実装済み。

メモリの都合でどの機能をmainに入れるか検討です。
入らなかった機能は、フォントが変更できないブランチを作ってそこでやるのがいいかなぁ。

**Comment by WarabiMkV** [comment]
確認しました。おーっ、良いですね。
hp42s に近づいてきてテンション上がってます。
フォントも気分に寄って替えられるのでそこも気に入ってるのですが…

そうですね、別ブランチかぁ、ありですね。

**Comment by WarabiMkV** [comment]
mainかなり良いですね。

この機能の便利さを実感してしまうと組み込んだものが欲しいですね。
もう流石にメモリの限界でしょうか。

**Comment by ypsilon-takai** [comment]
@WarabiMkV 
ソースを整理して空きを作ったので、mainブランチに盛り込みました。

ただ、EEPROMへの書き込みが頻繁に発生するようになるので、デフォルトで無効になるようになっています。 有効にするには、ソースのdefineの修正が必要です。

> // uncomment to enable stacks preservation
> //#define ENABLE_PRESERVE_STACKS

EEPROMの書き換えは100万回以上のようです。
1日1000ストロークで3年弱
1日100ストロークで27年
まあ、10年以上は楽に使えそうではありますので、そんなに気にしなくてもいいかなぁ。
`

**Comment by WarabiMkV** [comment]
ありがとうございました。確認しました。
いや〜良いですねー。最高です！

**Comment by ypsilon-takai** [comment]
よかったです。
