### ISSUE TITLE
LAST xの機能が欲しいですね。

### ISSUE THREAD

**Issue by ypsilon-takai** [ypsilon-takai/hobby-rpn#12]
@WarabiMkV さんからの要望です。

**Comment by ypsilon-takai** [comment]
LASTx の仕様がいま一つよくわからないんですよね。
何をLASTxとすべきなんだろうか。

**Comment by WarabiMkV** [comment]
WarabiMkVです。例で説明させていただきます。
4000+312=4312　を計算したかったとして4000[Ent] 311 [+]と入力してしまったとき
[LAST x] を押すと311がxレジスタに入るため続けて[-]を押すことによりもとの数字
4000に戻ります。そして正しい312[+]を押し4312となります。

入力前のXレジスタの値が、LAST xレジスタに残っている。
入力前のYレジスタの値は、スタックにそのまま残っているので修正できる。

HP-42S取扱説明書
http://h10032.www1.hp.com/ctg/Manual/c01094960.pdf
の48ページに載っていますのでご確認いただければと。

**Comment by ypsilon-takai** [comment]
コメントありがとうございます。

はい。そこはわかってるんですが、
- LASTxレジスタにxレジスタの値を入れるタイミング
  演算子が押されたときだけ？
- LASTxキーを押したときにxレジスタに入っている値をどうするか
  レジスタにプッシュしてしまっていいのか？

あたりがちょっとよくわからないんです。
とりあえず、
- 演算子が押されたときだけLASTxレジスタを更新
- LASTxを押したときはxレジスタの内容はプッシュ

でやってみようかと思います。

それで、おかしければ検討ってことで。

**Comment by WarabiMkV** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  高井様こんばんは。杉山です。あ、やっぱりそうですよね。んーそうですね、エンターではLASTxには入らないようですしね。ご検討いただきありがとうございます。今後ともよろしくお願いします。p.s. またフォントができましたら送らせていただきます。杉山英治                                                                                                                                             送信元: Android向けBlackBerry Hub+受信トレイ                                                                                                                                                                           From: ***@***.***送信済み: 2021年9月24日 20:59To: ***@***.***返信先: ***@***.***: ***@***.***; ***@***.***件名: Re: [ypsilon-takai/hobby-rpn] LAST xの機能が欲しいですね。 (#12)  
コメントありがとうございます。
はい。そこはわかってるんですが、
LASTxレジスタにxレジスタの値を入れるタイミング
演算子が押されたときだけ？LASTxキーを押したときにxレジスタに入っている値をどうするか
レジスタにプッシュしてしまっていいのか？
あたりがちょっとよくわからないんです。
とりあえず、
演算子が押されたときだけLASTxレジスタを更新LASTxを押したときはxレジスタの内容はプッシュ
でやってみようかと思います。
それで、おかしければ検討ってことで。

**Comment by ypsilon-takai** [comment]
@WarabiMkV 

lastx実装してみました。
まだmainブランチには入れていないので、lastx_buttonブランチをチェックアウトして使ってください。
0長押しでlastxになります。

機能がこれで問題ないかどうか確認いただけると助かります。

ちなみに、小数入れるときに0を残す修正も入っています。

**Comment by WarabiMkV** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  高井さまこんばんは。早速のご対応、ご連絡ありがとうございました。ただいま、電卓の端子にハンダ付け完了し、試そうとしたらパソコンのバッテリー切れである程度充電されないとアダプターを接続していても落ちてしまう状態です。確認でき次第ご連絡させていただきます。杉山英治                                                                                                                                             送信元: Android向けBlackBerry Hub+受信トレイ                                                                                                                                                                           From: ***@***.***送信済み: 2021年9月26日 0:42To: ***@***.***返信先: ***@***.***: ***@***.***; ***@***.***件名: Re: [ypsilon-takai/hobby-rpn] LAST xの機能が欲しいですね。 (#12)  

@WarabiMkV

lastx実装してみました。

機能がこれで問題ないかどうか確認いただけると助かります。

mainブランチには入れていないので、lastx_buttonブランチをチェックアウトして使ってください。

ちなみに、小数入れるときに0を残す修正も入っています。

**Comment by WarabiMkV** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  高井さまおはようございます。LASTxの確認させていただきました。完璧です。こんなに早く実現できるとは…　脱帽です。少数の０の件もありがとうございました。ますます使いやすくなりました。今後ともよろしくお願いします。杉山英治                                                                                                                                             送信元: Android向けBlackBerry Hub+受信トレイ                                                                                                                                                                           From: ***@***.***送信済み: 2021年9月26日 0:42To: ***@***.***返信先: ***@***.***: ***@***.***; ***@***.***件名: Re: [ypsilon-takai/hobby-rpn] LAST xの機能が欲しいですね。 (#12)  

@WarabiMkV

lastx実装してみました。

機能がこれで問題ないかどうか確認いただけると助かります。

mainブランチには入れていないので、lastx_buttonブランチをチェックアウトして使ってください。

ちなみに、小数入れるときに0を残す修正も入っています。

**Comment by WarabiMkV** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  高井さま漢字フォントできましたので送ります。杉山英治                                                                                                                                             送信元: Android向けBlackBerry Hub+受信トレイ                                                                                                                                                                           From: ***@***.***送信済み: 2021年9月26日 0:42To: ***@***.***返信先: ***@***.***: ***@***.***; ***@***.***件名: Re: [ypsilon-takai/hobby-rpn] LAST xの機能が欲しいですね。 (#12)  

@WarabiMkV

lastx実装してみました。

機能がこれで問題ないかどうか確認いただけると助かります。

mainブランチには入れていないので、lastx_buttonブランチをチェックアウトして使ってください。

ちなみに、小数入れるときに0を残す修正も入っています。

**Comment by ypsilon-takai** [comment]
lastx まずは気に入っていただけてよかったです。

ただ、たぶん、懸念事項であった、 ・xレジスタが lastxに入るタイミング  ・lastxを呼び出したときのxレジスタの扱いに の2点についてこうだったらいいなみたいなのが出てくると思うので、そのときは連絡いただければと思います。

**Comment by WarabiMkV** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  hp42sのマニュアルの例でも確認したので（結構トリッキーな使い方なので）文句なし期待通りです。                                                                                                                                             送信元: Android向けBlackBerry Hub+受信トレイ                                                                                                                                                                           From: ***@***.***送信済み: 2021年9月26日 18:17To: ***@***.***返信先: ***@***.***: ***@***.***; ***@***.***件名: Re: [ypsilon-takai/hobby-rpn] LAST xの機能が欲しいですね。 (#12)  
lastx まずは気に入っていただけてよかったです。
ただ、たぶん、懸念事項であった、 ・xレジスタが lastxに入るタイミング  ・lastxを呼び出したときのxレジスタの扱いに の2点についてこうだったらいいなみたいなのが出てくると思うので、そのときは連絡いただければと思います。

**Comment by WarabiMkV** [comment]
ごめんなさい。意外と簡単な使い方で違いが出ました。
165000×3+3×2700=503100
3の入力を使い回す方法で入力してみると

165000[Ent]
3×
[LASTx]とするとxに3が入るところまではhpの実機と同じですが
続けて2700を入力するとxに入っている3がyに行かず495000のまま
hp実機では
z:495000
y:3
x:2700

この電卓の現状は
z:0
y:495000
x:2700
のため[LASTx][Ent]で呼び出した3を確定する必要があります。

訂正いただけると助かります。

**Comment by ypsilon-takai** [comment]
レポートありがとうございます。

対応してみました。
計算結果は、165000 3×[lastx]2700×+ で 503100になるようになりました。

直したのは1行ですが、メモリ削減のため処理を整理したりしたので変分は多くなっちゃってます。

まだlastx_buttonブランチのままです。
使ってみてください。

**Comment by WarabiMkV** [comment]
修正ありがとうございました。
確認できました。再度マニュアルの例他も確認しました。
今度こそ大丈夫だと思います。

**Comment by ypsilon-takai** [comment]
ひとまず、これで、mainブランチに盛り込みました。
