### ISSUE TITLE
R↓（レジスタのロールダウン）機能も欲しいですね。

### ISSUE THREAD

**Issue by WarabiMkV** [ypsilon-takai/hobby-rpn#14]
使っているうちに、R↓（レジスタのロールダウン）機能も欲しくなってきました。

**Comment by ypsilon-takai** [comment]
xレジスタの内容が0の時にクリア(Ent長押し)するとロールダウンしますよ。
確認ください。

**Comment by WarabiMkV** [comment]
はい。確認できました。
1[Ent]
2[Ent]
3[Ent]
とした後、
クリアせずに[R↓]を押す毎にレジスタの内容を以下のようにループして欲しいです。
   　　↓　↓　↓　↓　↓
L:３　３　３　３　３　３
T:１　３　３　２　１　３
Z:２　１　３　３　２　１
Y:３　２　１　３　３　２
x:３　３　２　１　３　３

**Comment by ypsilon-takai** [comment]
ああ、そうか、R↓はそういう動作でしたね。

実現は簡単ですけど、適当なところにキーの空きがないのと、メモリが足りないのが問題ですね。

**Comment by WarabiMkV** [comment]
０長押しをR↓にして、シフト０でLASTxではどうでしょう？

**Comment by ypsilon-takai** [comment]
難しくなかったので、そのままmainブランチに入れました。

 R↓ シフト側の入れやすいところで÷に割り当ててみました。

どうですかね。

**Comment by WarabiMkV** [comment]
確認しました。
動作OKです。いい感じです。

**Comment by ypsilon-takai** [comment]
よさそうなので、クローズ
